In [1]:
### Import libraries

import numpy as np
import math
from numpy.linalg import inv

In [2]:
# the object coordinates as seen by the camera
T_cam_obj = np.array([[0, 1,  0,  1],
                      [1, 0,  0, 10],
                      [0, 0, -1,  9],
                      [0, 0,  0,  1]])

# the origin of the robot base coordinates as seen by the camera
T_cam_base = np.array([[1,  0,  0, -10],
                       [0, -1,  0,  20],
                       [0,  0, -1,  10],
                       [0,  0,  0,   1]])

#### Part (a) 

After the equipment has been set up and these coordinate systems have been established, someone rotated the camera $90^\circ$ about the $z$-axis of the camera. What is the position and orientation of the camera with respect to the robot’s base coordinate system?

We can get the homogeneous transformation matrix $T^{base}_{cam}$ expressing the camera as seen by the origin of the robot base by getting the inverse of the matrix $T^{cam}_{base}$:

In [3]:
## The original camera coordinate as seen by the base coordinate of the robot

T_base_cam = inv(T_cam_base)
print(T_base_cam)

[[ 1.  0.  0. 10.]
 [-0. -1. -0. 20.]
 [-0. -0. -1. 10.]
 [ 0.  0.  0.  1.]]


Next, we initialize an independent homogeneous rotation of $90^\circ$ about the $z$-axis matrix:

In [5]:
## Init an independent homogeneous rotation matrix

rot_z = lambda gamma : np.array([[round(math.cos(gamma),2), round(-math.sin(gamma),2), 0, 0],
                                 [round(math.sin(gamma),2),  round(math.cos(gamma),2), 0, 0],
                                 [                       0,                         0, 1, 0],
                                 [                       0,                         0, 0, 1]])

rot_z_90 = rot_z(math.pi/2)
print(rot_z_90)

[[ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


To find the position and orientation of the camera with respect to the robot's base coordinate system after the $90^\circ$-about-$z$-axis rotation of the camera, we need to find the corresponding homogeneous transformation matrix. 
    
It is worth noting that as we treat the robot's base coordinate system as the base, we can easily reach our goal by applying the dot product on 2 matrices $T^{base}_{cam}$ and $R^z_{90}$. Because, indeed, from the point of view of the robot base, it is all about the displacement of the camera.

In [6]:
# The coordinate of the camera in new position as seen by the robot’s base coordinate

T_base_newCam = np.dot(T_base_cam, rot_z_90)
print(T_base_newCam)

[[ 0. -1.  0. 10.]
 [-1.  0.  0. 20.]
 [ 0.  0. -1. 10.]
 [ 0.  0.  0.  1.]]


The position and orientation of **the camera with respect to the robot's base coordinate system** respectively are:
$\begin{bmatrix}
    10 \\ 20 \\ 10
    \end{bmatrix}$ and $\begin{bmatrix}
    0 & -1 & 0\\
    -1 & 0 & 0\\
    0 & 0 & -1
\end{bmatrix}$

#### Part (b) 

After the rotation happened in a), the object is also rotated by $90^\circ$ about the $x$-axis of the object and translated by 4 units along the rotated $y$-axis. What is the position and orientation of the object with respect to the robot’s base coordinate system? What is the position and orientation of the object with respect to the rotated camera coordinate system?

First, initialize an independent homogeneous rotation of $90^\circ$ about $x$-axis matrix $R^x_{90}$ and the translation by 4 units along the $y$-axis. Together, we obtain a matrix $H$ expressing all the transformations:

In [7]:
rot_x_90 = np.array([[1,0,0,0],
                     [0, round(math.cos(math.pi/2)), round(-math.sin(math.pi/2)), 0],
                     [0, round(math.sin(math.pi/2)), round(math.cos(math.pi/2)), 0],
                     [0,0,0,1]])

trans_4_y = np.array([[1,0,0,0],
                      [0,1,0,4],
                      [0,0,1,0],
                      [0,0,0,1]])

H_obj = np.dot(rot_x_90, trans_4_y)

print(H_obj)

[[ 1  0  0  0]
 [ 0  0 -1  0]
 [ 0  1  0  4]
 [ 0  0  0  1]]


With a similar argument as part (a), we have:

In [8]:
T_base_obj = np.dot(T_base_cam, T_cam_obj)
T_base_newObj = np.dot(T_base_obj, H_obj)
print(T_base_newObj)

[[ 0.  0. -1. 11.]
 [-1.  0.  0. 10.]
 [ 0.  1.  0.  5.]
 [ 0.  0.  0.  1.]]


The position and orientation of **the object with respect to the robot’s base coordinate system** respectively are:
    $\begin{bmatrix}
    11 \\ 10 \\ 5
    \end{bmatrix}$ and $\begin{bmatrix}
    0 & 0 & -1\\
    -1 & 0 & 0\\
    0 & 1 & 0
    \end{bmatrix}$

In [9]:
T_newCam_base = inv(T_base_newCam)
T_newCam_newObj = np.dot(T_newCam_base, T_base_newObj)
print(T_newCam_newObj)

[[ 1.  0.  0. 10.]
 [ 0.  0.  1. -1.]
 [ 0. -1.  0.  5.]
 [ 0.  0.  0.  1.]]


The position and orientation of **the object with respect to the rotated camera coordinate system** respectively are:
    
$\begin{bmatrix}
    10 \\ -1 \\ 5
    \end{bmatrix}$ and $\begin{bmatrix}
    1 & 0 & 0\\
    0 & 0 & 1\\
    0 & -1 & 0
\end{bmatrix}$